### ISSUE TITLE
Add support for  host_uri argument 

### ISSUE THREAD

**Issue by naorlivne** [nebula-orchestrator/nebula-cmd#59]
## Expected/Wanted Behavior
Now that https://github.com/nebula-orchestrator/nebula-python-sdk/pull/87 has been merged the cli should also allow supporting clusters who's manager API are on a non-standard path using the `host_uri` arg

## Actual Behavior
Can't configure the `host_uri` param used by nebula-cmd

@vineyyadav thinking you might want first crack at it as well?

**Comment by vineyyadav** [comment]
@naorlivne , do you want me to include the dist/nebulactl file also in the PR? Or it will be auto generated once the code changes are merged.

P.S. I have done the changes and tested them too.

**Comment by naorlivne** [comment]
No need to include the binary, it will be auto-generated, 10x.
